try
	colorscheme molokai
catch
	colorscheme default
endtry

" appearance
syntax on
set ai
set ci
set si
set ruler
set mouse=a
set cb=unnamedplus
set t_Co=256
set bg=dark
set cursorline
set showtabline=2
set splitbelow
set splitright
set scrolloff=10

" search
set ignorecase
set smartcase
set hlsearch
set incsearch

" ban
set nofoldenable
set nocompatible
set noexpandtab

" tab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" file type
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on

" wrap
set wrap
set linebreak

" below mode
set showmode " default
set showcmd 

" fast exit
inoremap jk <C-[><Right>
inoremap jj <C-[><Right>

" set jk waiting time
set timeout
set timeoutlen=500

" undo memory
set undofile
set undodir=~/.vim/vimundo/

" shift-page up/down move line
nnoremap <S-PageUp> :m-2<CR>
nnoremap <S-PageDown> :m+<CR>
inoremap <S-PageUp> <Esc>:m-2<CR>i
inoremap <S-PageDown> <Esc>:m+<CR>i

" copy to end
nnoremap Y y$

" remember the cursor postition last time
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$")  | exe "normal! g'\"" | endif

" change cursor style
" Ps = 0  -> blinking block.
" Ps = 1  -> blinking block (default).
" Ps = 2  -> steady block.
" Ps = 3  -> blinking underline.
" Ps = 4  -> steady underline.
" Ps = 5  -> blinking bar (xterm).
" Ps = 6  -> steady bar (xterm).
let &t_EI = "\e[2 q"  " Normal mode  : block
let &t_SI = "\e[6 q"  " Insert mode  : beam
let &t_SR = "\e[4 q"  " Replace mode : underline

if !exists('nvim') && !exists('vscode') && filereadable('/home/pacfrog/.vim/MyVimConf.vim')
	source /home/pacfrog/.vim/MyVimConf.vim
endif
