try
	colorscheme sorbet
catch
	colorscheme zaibatsu
endtry

" appearance
syntax on
set ai
set ci
set si
set ruler
set mouse=a
set cb=unnamedplus
set t_Co=256
set bg=dark
set cursorline
set showtabline=2
set splitbelow
set splitright
set scrolloff=10

" search
set ignorecase
set smartcase
set hlsearch
set incsearch

" ban
set nofoldenable
set nocompatible
set noexpandtab

" tab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" file type
filetype on
filetype indent on
filetype plugin on

" wrap
set wrap
set linebreak

" below mode
set showmode " default
set showcmd 

" fast exit
inoremap jk <C-[><Right>
inoremap jj <C-[><Right>

if !exists('nvim') && !exists('vscode') && filereadable('/home/justin/.vim/MyVimConf.vim')
	source /home/justin/.vim/MyVimConf.vim
endif

if isdirectory('/home/justin/.vim/vimundo')
	" undo memory
	set undofile
	set undodir=/home/justin/.vim/vimundo
endif
