# frog's aliases
alias pwd='pwd && pwd | xclip -sel clipboard'
alias lsn='stat -c "%a %A %n"'
alias fl='ranger'
alias v='vim'
alias V='vim --clean'
alias vconf='vim ~/.vimrc'
alias rm='rm -i'
alias sl='sl -e'
alias fd='fdfind'
alias lvl='echo $SHLVL'
alias tty-clock='tty-clock -bsctC 6'
alias fps='mangohud'
alias diff='diff --color'
alias fzfp='fzf --preview "batcat --color always {}"'
alias :q='exit'
alias :q!='exit'

# bookmarks
alias home='cd ~/; ll'
alias dl='cd ~/Downloads; ll'
alias docs='cd ~/Documents; ll'
alias pics='cd ~/Pictures; ll'
alias vids='cd ~/Videos; ll'
alias musics='cd ~/Music; ll'
alias dots='cd ~/gitroot/dotfiles; ll'
alias works='cd ~/workspace; ll'
alias proj='cd ~/workspace/proj; ll'
alias tmp='cd ~/tmp; ll'
